FROM golang:1.19.3-alpine as builder
WORKDIR /app 
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
  -ldflags="-s -w -X 'gitlab.com/TitanInd/proxy/proxy-router-v3/internal/config.BuildVersion=$(grep '^VERSION=' .version | cut -d '=' -f 2-)'" \
  -o bin/hashrouter cmd/main.go && \
  cp /bin/sh /app/sh && chmod +x /app/sh

FROM scratch
WORKDIR /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/bin/hashrouter /usr/bin/
COPY --from=builder /app/sh /bin/sh

SHELL ["/bin/sh", "-c"]

# baking envs into the image
ARG ETH_NODE_ADDRESS
ENV ETH_NODE_ADDRESS=$ETH_NODE_ADDRESS

ARG ETH_NODE_LEGACY_TX
ENV ETH_NODE_LEGACY_TX=$ETH_NODE_LEGACY_TX

ARG ENVIRONMENT
ENV ENVIRONMENT=$ENVIRONMENT

ARG HASHRATE_CYCLE_DURATION
ENV HASHRATE_CYCLE_DURATION=$HASHRATE_CYCLE_DURATION

ARG HASHRATE_VALIDATION_START_TIMEOUT
ENV HASHRATE_VALIDATION_START_TIMEOUT=$HASHRATE_VALIDATION_START_TIMEOUT

ARG HASHRATE_SHARE_TIMEOUT
ENV HASHRATE_SHARE_TIMEOUT=$HASHRATE_SHARE_TIMEOUT

ARG HASHRATE_ERROR_THRESHOLD
ENV HASHRATE_ERROR_THRESHOLD=$HASHRATE_ERROR_THRESHOLD

ARG HASHRATE_ERROR_TIMEOUT
ENV HASHRATE_ERROR_TIMEOUT=$HASHRATE_ERROR_TIMEOUT

ARG CLONE_FACTORY_ADDRESS
ENV CLONE_FACTORY_ADDRESS=$CLONE_FACTORY_ADDRESS

ARG CONTRACT_MNEMONIC
ENV CONTRACT_MNEMONIC=$CONTRACT_MNEMONIC

ARG WALLET_PRIVATE_KEY
ENV WALLET_PRIVATE_KEY=$WALLET_PRIVATE_KEY

ARG MINER_VETTING_DURATION
ENV MINER_VETTING_DURATION=$MINER_VETTING_DURATION

ARG MINER_SHARE_TIMEOUT
ENV MINER_SHARE_TIMEOUT=$MINER_SHARE_TIMEOUT

ARG LOG_TO_FILE
ENV LOG_TO_FILE=$LOG_TO_FILE

ARG LOG_COLOR
ENV LOG_COLOR=$LOG_COLOR

ARG LOG_LEVEL_APP
ENV LOG_LEVEL_APP=$LOG_LEVEL_APP

ARG LOG_LEVEL_CONNECTION
ENV LOG_LEVEL_CONNECTION=$LOG_LEVEL_CONNECTION

ARG LOG_LEVEL_PROXY
ENV LOG_LEVEL_PROXY=$LOG_LEVEL_PROXY

ARG LOG_LEVEL_SCHEDULER
ENV LOG_LEVEL_SCHEDULER=$LOG_LEVEL_SCHEDULER

ARG POOL_ADDRESS
ENV POOL_ADDRESS=$POOL_ADDRESS

ARG POOL_CONN_TIMEOUT
ENV POOL_CONN_TIMEOUT=$POOL_CONN_TIMEOUT

ARG PROXY_ADDRESS
ENV PROXY_ADDRESS=$PROXY_ADDRESS

ARG SYS_ENABLE
ENV SYS_ENABLE=$SYS_ENABLE

ARG SYS_LOCAL_PORT_RANGE
ENV SYS_LOCAL_PORT_RANGE=$SYS_LOCAL_PORT_RANGE

ARG SYS_NET_DEV_MAX_BACKLOG
ENV SYS_NET_DEV_MAX_BACKLOG=$SYS_NET_DEV_MAX_BACKLOG

ARG SYS_RLIMIT_HARD
ENV SYS_RLIMIT_HARD=$SYS_RLIMIT_HARD

ARG SYS_RLIMIT_SOFT
ENV SYS_RLIMIT_SOFT=$SYS_RLIMIT_SOFT

ARG SYS_SOMAXCONN
ENV SYS_SOMAXCONN=$SYS_SOMAXCONN

ARG SYS_TCP_MAX_SYN_BACKLOG
ENV SYS_TCP_MAX_SYN_BACKLOG=$SYS_TCP_MAX_SYN_BACKLOG

ARG WEB_ADDRESS
ENV WEB_ADDRESS=$WEB_ADDRESS

ARG WEB_PUBLIC_URL
ENV WEB_PUBLIC_URL=$WEB_PUBLIC_URL

EXPOSE 3333 8081

ENTRYPOINT ["hashrouter"]